### ISSUE TITLE
onChange output

### ISSUE THREAD

**Issue by kali-musquare** [Aurelain/react-style-editor#1]
while creating new class , attributes are repeating itself.

**Comment by Aurelain** [comment]
Thanks, I'll look into it soon and maybe also fix some other minor issues.

**Comment by Aurelain** [comment]
Resolved in [v0.3.0](https://github.com/Aurelain/react-style-editor/releases/tag/v0.3.0).

**Comment by kali-musquare** [comment]
> Resolved in [v0.3.0](https://github.com/Aurelain/react-style-editor/releases/tag/v0.3.0).

Thank you so much Aurelain.
