### ISSUE TITLE
Is there any contribution guide?

### ISSUE THREAD

**Issue by ravisojitra** [Aurelain/react-style-editor#7]
I'm planning to use this project for my requirement but it's missing one feature which is dropdown suggestion, So I'm planning to add support of that feature and going to commit back.

So is there any particular contribution guide?

**Comment by Aurelain** [comment]
Hi, Ravi.
I added the [CONTRIBUTING.md](https://github.com/Aurelain/react-style-editor/blob/master/CONTRIBUTING.md) just now.
As mentioned there, I am willing to review and accept pull-requests, but:
1. My actions will be pretty slow, as I foresee a pretty busy year ahead.
2. I don't have a lot of familiarity with this process on GitHub.

**Comment by ravisojitra** [comment]
There are 2 points I would like to ask:

1. Since you have mentioned not creating dependencies with other packages, I have used the react-autosuggest npm package for dropdown. If that doesn't work for you, I'll not create PR and will keep my changes with me.
2. There's no proper dev environment setup, so I'm thinking of using microbundle-crl to improve the dev experience which will help you debug faster and release this library in a better way.

**Comment by Aurelain** [comment]
1. I feel a bit awkward trying to keep the dependencies at zero, but I'm not yet ready to let this go :).
2. The developer experience can be improved in simpler ways, maybe just by having a special entry-point for the CreateReactApp that now resides in `/website`.

Feels like contributing is not so welcoming, sorry about that... It's ok if you decide to go your own way.
